### ISSUE TITLE
Update pouchdb-adapter-websql-core

### ISSUE THREAD

**Issue by sofiageo** [craftzdog/pouchdb-adapter-react-native-sqlite#11]
The current version of the library is giving an error when using where() with sort() in RxDB - It looks like gaodeng has forked and fixed this issue on his repository: https://github.com/gaodeng/pouchdb-adapter-websql-core 

Do you think it's possible to merge the changes or create a similar implementation? Thanks

**Comment by craftzdog** [comment]
If he published the fork to npm, we can use it instead.
The best scenario would be that his fork gets merged into the original package.
So please ask him to do so, or let them know you need it on [the issue](https://github.com/pouchdb/pouchdb/issues/7011).

**Comment by sofiageo** [comment]
It seems that there was intent to keep maintaining the websql core package but somehow it got lost in the communication [here](https://github.com/pouchdb/pouchdb/issues/7885) I will try to inform gaodeng in case he can ask for the repo to be added in the pouchdb community. 

I would do it myself but I think I would be a terrible maintainer for a project I have no idea about :)

**Comment by gaodeng** [comment]
@sofiageo  for pouchdb 7.1.1，you can use this in your package.json
```js
{
    "pouchdb-adapter-react-native-sqlite": "git+https://github.com/gaodeng/pouchdb-adapter-react-native-sqlite.git#7.1.1",
}
```

**Comment by sofiageo** [comment]
Hi @gaodeng and thanks for the fixes, I'm already using your package, I'm just trying to help with organizing the next steps. Neither pubkey (RxDB maintainer) or craftzdog were aware of the issues the abandoned websql-core version was causing. 

While I think it's great someone can maintain the package for the future, maybe it would also be better to put it under https://github.com/pouchdb-community - for various reasons (package easier to find, no need to change the url every time someone else will fork the project, etc)

If you don't want to put it under the community repo I understand, however, having two pouchdb-adapter-react-native-sqlite will also be confusing. What I'm trying to ask without being ungrateful is, why not collaborate with the other projects / maintainers instead of forking everything?

**Comment by gaodeng** [comment]
I like pouchdb a lot, but unfortunately the pouchdb main code repository seems to have been abandoned, It doesn't make sense to spend time maintaining its submodules

**Comment by hosseinmd** [comment]
It seems there is nothing to grow pouchdb in react-native.
Realm library is very popular, but it is not useful for cross platform, in this case pouchdb is great.
However, now what can we do to improve pouchdb.

**Comment by craftzdog** [comment]
Merged @gaodeng's patch.
