### ISSUE TITLE
Use LevelDB instead of SQLite

### ISSUE THREAD

**Issue by mqtik** [craftzdog/pouchdb-adapter-react-native-sqlite#15]
Hi.
I saw a bunch of packages for running PouchDB on React Native using SQLite.

This is what I´m proposing:

What if we transition everything into one repo, using LevelDB?

**Comment by mqtik** [comment]
@craftzdog https://github.com/greentriangle/react-native-leveldb

**Comment by craftzdog** [comment]
You have to solve `\u0000` issue yourself
