### ISSUE TITLE
Get performance degrades 10x

### ISSUE THREAD

**Issue by chmac** [craftzdog/pouchdb-adapter-react-native-sqlite#4]
I'm new to PouchDB / CouchDB. Very excited to find your package on account of the performance gains. Alas, I'm seeing performance problems. I guess it's something on my side, but I'm not sure how to investigate / debug. Any input would be greatly appreciated.

I have 3 PouchDB databases which are doing one way replication from a cloudant instance. The databases are ~8k records 22MB, ~150 records 210k, ~3.5k records 5MB. The data is synced very quickly into my local PouchDB databases.

I can `.allDocs()` on the ~150 record database in ~200ms. Performance is great.

I'm trying to fetch ~350 documents from the database with 8k records. If I use `.allDocs({keys: [...]})` it takes >40s to load the data. If I iterate with a `Promise.each([...])` (from bluebird) to fetch each record serially via `.get(id)`, each fetch can take up to 3s or more.

If I disable `{ adapter: "react-native-sqlite" }` line, then performance is significantly better in the iOS simulator. The ~350 documents load in ~4s (via the serial fetch method).

Any advice on how I can debug this issue?

**Comment by craftzdog** [comment]
I guess it may be an issue on [react-native-sqlite-2](https://github.com/craftzdog/react-native-sqlite-2). It seems that there're some overheads.
It's performant when you use `startkey` and `endkey` instead of specifying individual keys.
So I recommend you to use indices so that you can get multiple documents with one query.

**Comment by chmac** [comment]
Thanks, that approach is definitely more performant for fetching child documents by their parent IDs. Unfortunately that means it takes ~700ms to get a single document by its own ID on an index. :-) I guess that’s survivable. In the end it seems like read performance is more or less linear.

One question, it looks like **writes** are significantly slower with sqlite than with AsyncStorage. Any performance optimisation suggestions on that side? Is PouchDB maybe doing some kind of sort to insert each new document at the correct place in the index? Maybe if we assemble our whole dataset first, then push it into CouchDB in sequence, and then sync that sequentially sorted data to PouchDB we’ll get better write performance?

At some point we’ll also try to ship the initial data set as part of the app build, but that’s a challenge for another day... :-)

**Comment by craftzdog** [comment]
[bulkDocs](https://pouchdb.com/guides/bulk-operations.html) would be more performant than calling `put` many times.
If it's slower than AsyncStorage, there're also some overheads in writing docs. I guess that's because it's based on `pouchdb-adapter-websql-core` implementation.
Hope it helps.

**Comment by chmac** [comment]
@craftzdog It's the `PouchDB.replicate()` that is extremely slow. We're replicating a database of ~9k records, total ~20MB of data, and it can take ~20 minutes to sync the data. While it's maybe 10x faster with AsyncStorage. But then getting the data back is 2x or so faster with sqlite. :-)

Any optimisation strategies / advice for the replication process? I'd assume it uses `bulkDocs()` under the hood, but I'm not sure.

**Comment by chmac** [comment]
PS: Thanks for the advice so far, that `startkey` / `endkey` optimisation has gotten us from unacceptable performance into the realm of acceptable, really appreciate it.

**Comment by craftzdog** [comment]
Glad it works.

You can specify `batch_size` option to `replicate()` in order to increase number of docs to process at a time. This option reduces iterations for the replication, so it would speed up.
See the documentation: https://pouchdb.com/api.html#replication

**Comment by chmac** [comment]
Thanks, will look into the `batch_size` option. We're seeing 100 inserts at a time taking 10s to 20s, so 100ms per insert. Perhaps larger batches would also take 10s to 20s, so we could try inserting maybe 1k records at a time, then we might get the whole 9k inserted in 2 minutes or so. Still seems like an awful lot of time, but definitely a huge improvement over 20 minutes!

**Comment by craftzdog** [comment]
I guess it's ok to close. Thanks
