### ISSUE TITLE
pouchdb allDocs with specific keys return all documents in Database

### ISSUE THREAD

**Issue by Winglonelion** [craftzdog/pouchdb-adapter-react-native-sqlite#7]
First, thanks for your great adapter and SQLite library for React Native, it save a lots day of us when implement CouchDb in mobile.  

But, from PouchDb 6.4 when use allDocs API with `keys` option always return all documents in Database.

I think it relation with some change in allDocs API of PouchDB: https://github.com/pouchdb/pouchdb/releases/tag/6.4.0

And react-native-sql2 had incompatable with new change. 

Because `react-native-sql2` not have direct relation with React Native, so i post this issue here.

Similiar Issue here: https://github.com/pouchdb/pouchdb/issues/7007

Hope to receive your respond soon

**Comment by craftzdog** [comment]
As this adapter is ported from `pouchdb-adapter-cordova-sqlite`, let's track how they will solve the problem on https://github.com/pouchdb-community/pouchdb-adapter-cordova-sqlite/issues/83

At the moment, I recommend you to use PouchDB@5 which is totally stable in [my RN app](https://www.inkdrop.info/) on production.

**Comment by Winglonelion** [comment]
i see, seem like @6.3.4 also work fine. I will try it more and feedback late. Thanks
