### ISSUE TITLE
[ Feature Request ] support pre-populated database

### ISSUE THREAD

**Issue by gaodeng** [craftzdog/pouchdb-adapter-react-native-sqlite#8]

**Comment by deeuu** [comment]
@craftzdog are prebuilt DBs supported, e.g. as demonstrated  [On this post](https://pouchdb.com/2016/04/28/prebuilt-databases-with-pouchdb.html)?

Thanks for the great work!

**Comment by craftzdog** [comment]
No. PR would be appreciated!

**Comment by craftzdog** [comment]
Copy a pre-populated sqlite file to the default database path, then open it via PouchDB.

For more detail: https://ospfranco.notion.site/Configuration-6b8b9564afcc4ac6b6b377fe34475090
