### ISSUE TITLE
CDB replication + local query is broken

### ISSUE THREAD

**Issue by greenais** [craftzdog/pouchdb-adapter-react-native-sqlite#9]
I step in your pouchdb adapter in hope to find working solution for bundle of pouchdb on RN + couchdb backend.
But it seems that sqlite is broken in the same manner as asyncstorage is, details are [here](https://github.com/stockulus/pouchdb-react-native/issues/105)
Both - mapreduce and find plugins show exactly same behaviour: after changed docs replication from CDB query starts to show only last updated on server doc, nevertheless all other docs remain untouched in local PDB. 
My first question: 
is there any chance that this bug will be resolved in a some visible future?

PDBRN seems unmantained (at least since August), but the only unique thing there is asyncstorage adapter, the rest could be combined of recent pouchdb-core + plugins.

But your adapter depends on PDBRN, so my second question:
is there any way to use sqlite adapter in counjunction with pure PDB, without need of  PDBRN?

**Comment by craftzdog** [comment]
> is there any chance that this bug will be resolved in a some visible future?
No. It is nothing to do with the bug as it is just an adapter. Use older version.

> is there any way to use sqlite adapter in counjunction with pure PDB, without need of PDBRN?
I'm not sure because it's not tested with pure PouchDB

**Comment by greenais** [comment]
@badbod99 Thank you for your suggestoins.
So you don't experience any of mentioned above issues with broken find/mapreduce outputs after changed docs replication in your expo setup, right?
If I don't use expo (just vanilla RN) - is there way to use SQLiteAdapterFactory then?
This import looks quite new for me:
`import SQLiteAdapterFactory from '../adapters/SQLiteAdapter';`
Where it comes from?

**Comment by badbod99** [comment]
Not yet tested find or map reduce fully, but since it's on the latest PouchDB with WebSQL doing the SQL generation, I don't expect any issues. 

The SQLLiteAdapter file is just the .js file for the adapter taken from this project. Moved it locally as this project currently references 6.4.1 and we want 7.0.0 where (I suspect) many of the issues are resolved.

Without expo you'll need another SQLite implementation such as https://github.com/craftzdog/react-native-sqlite-2

**Comment by craftzdog** [comment]
Thanks for the suggestion, @badbod99.

Made [websql-core-7.0.0](https://github.com/craftzdog/pouchdb-adapter-react-native-sqlite/tree/websql-core-7.0.0) branch for this issue.
Released `pouchdb-adapter-react-native-sqlite@2.0.0` with beta tag on npm so you can try it.
If it worked as expected, I would drop the beta.

**Comment by badbod99** [comment]
@craftzdog - Seems that replication is broken with this setup.  It works fine with remote debugger attached (i.e. running through web worker with Expo), but not without.  I'm going to try and debug it.

**Comment by craftzdog** [comment]
I guess PouchDB uses APIs that JSC doesn't support because it is not a web browser.

**Comment by badbod99** [comment]
Managed to sort it. Had to manually add atob and broad implementions to global.  Not yet tested attachments, but otherwise all working. I'll create a report with the custom PouchDB build, you could then reference that in your docs rather than pouchdv-react-native.

**Comment by greenais** [comment]
@badbod99 did you managed to create a repo with the custom PouchDB build as you planned?
I'd ready to test it against issues I mentioned in initial issue - they are still actual for PDBRN, unfortunately..

**Comment by badbod99** [comment]
I've got an example up, it's basic but working. Still planning to setup a repo to replace pdbrn properly, but still testing all features. Example project here https://github.com/badbod99/pouchdb-expo-example

**Comment by greenais** [comment]
Thank you for an update.
Please let me know here or via PM when you set up repo - I'm ready to collaborate in testing from vanilla RN side - I have existing CDB + PDBRN project with almost comprehensive PDB functionality involved, but attachments
